import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ViewResume from "@/components/Home/ViewResume";

const myFont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        {children}
        <ViewResume />
      </body>
    </html>
  );
}
